apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-management-deployment
  labels:
    app: book-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-management
  template:
    metadata:
      labels:
        app: book-management
    spec:
      containers:
        - name: book-management
          image: muna18/book-management:latest
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20

